### ISSUE TITLE
Find out which deployment is stable and tag it

### ISSUE THREAD

**Issue by froi** [Code4PuertoRico/contratospr-api#146]
## What is going on

We are having problems with our dependencies when deploying to Heroku. The test we are doing locally are not showing us the issue. While we figure out what is going on we need to find out which deployed version is the most stable, create a tag, and mark it as a release.

Making a release will let us deploy a specific tag with confidence and will permit us rollback to a version. It will also give us confidence in deploying a project state.

For now I've removed automatic deployments from our master branch to ensure that the application will not be affected by our work.

## Discovery / investigation

The activity in Heroku shows the following rolbacks:

v193 (rollback to 191) 
----> v191 (Update REDIS by heroku-redis)
--------> v190 (Rollback to v185) -> v185 (rollback to v181)
------------> v181 (Update REDIS by heroku-redis)
----------------> v175 (last non rollback or deployment error version) - hash ece048a8

I've narrowed it down to these three hashes:

- 9cfbf26 - 8 days ago (Update dependencies)
- a88184e - 9 days ago (Changing app server to gunicorn)
- 96ba667 - 12 days ago (Django version dump from Dependabot)
- 0a66ba9 - 12 days ago (GitHub Action workflow file change)
- 5c25abf - 12 days ago
- b8b5ed5 - 5 months ago
- ece048a8 - 5 months ago

**Comment by jpadilla** [comment]
https://github.com/Code4PuertoRico/contratospr-api/releases/tag/v1.2.0
